kind: Job
apiVersion: batch/v1

metadata:
  name: semipatch-100p

spec:
  template:
    spec:
      containers:
      - name: semipatch-100p
        image: "basscoma/deepclustering:gpu0.9"
        workingDir: /storage/deepcluster_P2/semi/100p
        command: ["python", "main_echogram_semi_3classes.py"]
        resources:
          limits:
            cpu: "4"
            memory: 32Gi
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
