kind: Job
apiVersion: batch/v1

metadata:
  name: deepcl-unsup

spec:
  template:
    spec:
      containers:
      - name: deepcl-unsup
        image: "basscoma/deepclustering:gpu0.4"
        workingDir: /storage/deepcluster
        command: ["python", "main_echogram.py"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
#      resources:
#        limits:
#          cpu: "4"
#          memory: 16Gi
      restartPolicy: OnFailure
  backoffLimit: 0
