kind: Job
apiVersion: batch/v1

metadata:
  name: semipatch-100p-feature

spec:
  template:
    spec:
      containers:
      - name: semipatch-100p-feature
        image: "basscoma/deepclustering:gpu0.9"
        workingDir: /storage/deepcluster_P2/semi/feature_maker_100p
        command: ["python", "main_echogram_semi_3classes.py"]
        resources:
          limits:
            cpu: "2"
            memory: 21Gi
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
